execution_env=local
#execution_env=remote
appURL1=http://localhost/opencart/upload/
appURL2=https://tutorialsninja.com/demo/
email=Test101@yopmail.com
password=123456
#password=123456454    
searchProductName=iPhone